### ISSUE TITLE
Vector "content" doesn't return string data correctly in Salt text editor

### ISSUE THREAD

**Issue by Lamby777** [Lamby777/YALS#1]
Below the line and column numbers, it shows the content vector in string form. Unfortunately, I'm a huge noob in C++ and have no clue how to correctly output the content of the vector. It outputs in some strange mojibake or something, not sure. Couldn't find out the problem with the internet, so hopefully someone else can help out with this.

**Comment by r33m-m1kul5k1** [comment]
Hey, I would like to help you can you specify the problem and explain a little about the project?
Moreover can you redirect me to resources on how to run this program?

**Comment by Lamby777** [comment]
> Hey, I would like to help you can you specify the problem and explain a little about the project? Moreover can you redirect me to resources on how to run this program?

Thanks, this project is meant to run on Linux, but I think it's still somewhat compatible with Windows with some edits. I'm making it to learn C++ as a new language. To compile it, make sure you have ncurses installed on your system. Then, run `make` inside the Release directory. Once the binary is made, run it and then run the command `salt` inside the shell to bring up the text editor.
On the 10th and 11th lines, there is some debug information that might help explain my problem. The first line shows the last input's X and Y positions, and the bottom line is what gets shown when you try printing lines from the `vector<string>` variable `content` that stores the current text file's information. Also, don't press enter in the editor, since it causes a different error that I'm currently working on. (Still learning about vectors in C++ :/)

**Comment by Lamby777** [comment]
Solved with the string.c_str() method. String object didn't actually output a string because it was an object... I think?
Commit #13, by the way.
